import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillYoutube, AiFillGithub, AiFillMediumSquare} from 'react-icons/ai'
import Image from 'next/image'
import Adam from '../public/Adam.png'
import code from '../public/code.png'
import design from '../public/design.png'
import db from '../public/db.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>developedbyadam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 '>
        <section className="min-h-screen">
          <nav className='py-10 mg-12 flex justify-between' >
            <h1 className='text-xl'>developedbyadam</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>       
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-500 font-medium'>Adam Khodier</h2>
            <h3 className='text-2xl py-2'>Full Stack Software Engineer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Brand new full stack software developer open to work. Check me out with the links down below!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-teal-500'>
            <a href='#'><AiFillLinkedin/></a>
            <a href='#'><AiFillYoutube/></a>
            <a href='#'><AiFillGithub/></a>
            <a href='#'><AiFillMediumSquare/></a>
          </div>
          <div className='flex justify-center py-3'>
            <Image className='rounded-full w-60 h-60' src={Adam}/>
          </div>
        </section> 
        <section>
          <div className='text-center p-10'>
            <h3 className='text-3xl py-1'>Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">I have recently started my new journey as a full stack software engineer and can offer my programming and web design skills on the front end as well as the back end to help my clients create robust web applications.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Code Your Project
              </h3>
              <p className="py-2">
              Do you have an idea for your next great website? Let's make it a
              reality.
              </p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Ruby on Rails</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600"> Web Design Tools I Use</h4>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={db} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Database Organization
              </h3>
              <p className="py-2">
                Creating and organizing database tables with proper relationship functionality.
              </p>
              <h4 className="py-4 text-teal-600"> Web Design Tools I Use</h4>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">SQLite</p>

            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
